use db_daily_principle;
CREATE TABLE IF NOT EXISTS t_wechat_articles (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  url VARCHAR(512) NOT NULL UNIQUE,
  title VARCHAR(256) NOT NULL,
  author VARCHAR(128) DEFAULT '',
  published_at DATETIME NULL,
  cover_image VARCHAR(512) DEFAULT '',
  content_html MEDIUMTEXT NOT NULL,
  content_text MEDIUMTEXT NOT NULL,
  tag VARCHAR(64) DEFAULT '每日原则',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;